name: HomeLab Tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of tests to run'
        required: true
        default: 'All'
        type: choice
        options:
          - All
          - Unit
          - Integration
          - Workflow

jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup PowerShell
      uses: actions/setup-powershell@v1
      with:
        powershell-version: '7.2'
    
    - name: Install required modules
      shell: pwsh
      run: |
        Install-Module -Name Pester -Force -SkipPublisherCheck
        Install-Module -Name Az.Accounts -Force -SkipPublisherCheck
        Install-Module -Name Az.Resources -Force -SkipPublisherCheck
        Install-Module -Name Az.Network -Force -SkipPublisherCheck
        Install-Module -Name Az.Websites -Force -SkipPublisherCheck
        Install-Module -Name Az.Dns -Force -SkipPublisherCheck
    
    - name: Run tests
      shell: pwsh
      run: |
        $testType = '${{ github.event.inputs.test_type }}'
        if ([string]::IsNullOrEmpty($testType)) {
          $testType = 'All'
        }
        
        Write-Host "Running $testType tests..."
        cd tests
        ./Run-HomeLab-Tests.ps1 -TestType $testType -GenerateReport
      
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: |
          tests/TestResults.xml
          tests/TestReport.html
    
    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: tests/TestResults.xml